image: gitpod/workspace-full

tasks:
  - name: Check workspace size
    command: | 
      STOPPING="2m"
      if [ "$GITPOD_WORKSPACE_CLASS" == "g1-xlarge" ] || [ "$GITPOD_WORKSPACE_CLASS" == "g1-xxlarge" ]
      then
        echo ""
        echo "Attention! This workspace has been started with workspace class $GITPOD_WORKSPACE_CLASS,"
        echo "but classes "g1-xlarge" and "g1-xxlarge" are currently not available.
        echo "Please make sure to select a smaller class when starting the workspace."
        echo "This message is a workaround until the choice of workspace classes has been reduced."
        echo ""
        echo ""
        echo "To save costs, this workspace will be stopped in $STOPPING"
        sleep "$STOPPING"
        gp stop
      fi

